### ISSUE TITLE
Update recipes to use Treated Wood

### ISSUE THREAD

**Issue by alexanderheuts** [MaienM/ThisIsFine#20]
- [ ] Wooden Axle
- [ ] Wooden Gear

**Comment by MaienM** [comment]
Wooden gears can also be acquired by sawing a corner block of any type of wood. I've left this as-is for now, since getting a saw to work requires an axle and is thus already gated behind treated wood, but this could be adjusted to only work for treated wood corners if we want (and the other corners could then just give sawdust or sticks or something).
